### ISSUE TITLE
Fajny pomysł. Ale coś mi nie chce działać

### ISSUE THREAD

**Issue by pogarek** [apqlzm/medihunter#1]
Witaj

Na Windows 10 z Python 2.7 mam tak:
```
Traceback (most recent call last):
  File "C:\Python27\medihunter\Scripts\medihunter-script.py", line 11, in <module>
    load_entry_point('medihunter', 'console_scripts', 'medihunter')()
  File "c:\python27\medihunter\lib\site-packages\pkg_resources\__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "c:\python27\medihunter\lib\site-packages\pkg_resources\__init__.py", line 2793, in load_entry_point
    return ep.load()
  File "c:\python27\medihunter\lib\site-packages\pkg_resources\__init__.py", line 2411, in load
    return self.resolve()
  File "c:\python27\medihunter\lib\site-packages\pkg_resources\__init__.py", line 2417, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "c:\python27\medihunter\medihunter.py", line 42
    f'(iteration: {counter}) No results found', fg='yellow'))
```

Pozdrawiam serdecznie

**Comment by apqlzm** [comment]
Wygląda na to że wywala się na f-stringach.
Skrypt działa z pythonem w wersji 3.6 lub nowszej.
