### ISSUE TITLE
403 after log-in

### ISSUE THREAD

**Issue by Krandelbord** [apqlzm/medihunter#21]
Each time I try to do search I get this stacktrace.
Same user/password was used before. For some reason it stopeed working. 
Passowrd is correct - just checked that.
medicover_session.py 150 response status is http_403

`
Traceback (most recent call last):
  File "medihunter.py", line 282, in <module>
    medihunter()
  File "/home/emil/medihunter-venv/lib/python3.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/emil/medihunter-venv/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/emil/medihunter-venv/lib/python3.7/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/emil/medihunter-venv/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/emil/medihunter-venv/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "medihunter.py", line 182, in find_appointment
    disable_phone_search=disable_phone_search
  File "/home/emil/medihunter/medicover_session.py", line 236, in search_appointments
    appointments = self._parse_search_results(result)
  File "/home/emil/medihunter/medicover_session.py", line 159, in _parse_search_results
    result = result.json()
  File "/home/emil/medihunter-venv/lib/python3.7/site-packages/requests/models.py", line 900, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

`

**Comment by apqlzm** [comment]
Thank you for pointing that out.
The issue should be fixed with commit f0252dfe490deb873f0659c8e60876c526dee4e5
