### ISSUE TITLE
Missing retry after HTTPError: 500 Server Error

### ISSUE THREAD

**Issue by wrozwad** [apqlzm/medihunter#26]
I receive this error pretty often after +- 200–400 iterations:
```
Traceback (most recent call last):
  File "/home/sos/.local/bin/medihunter", line 11, in <module>
    load_entry_point('medihunter', 'console_scripts', 'medihunter')()
  File "/usr/lib/python3/dist-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3/dist-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3/dist-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3/dist-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/mnt/c/Users/sos/medihunter/medihunter.py", line 172, in find_appointment
    found_appointments = med_session.search_appointments(
  File "/mnt/c/Users/sos/medihunter/medicover_session.py", line 253, in search_appointments
    self.check_response_correctness(result)
  File "/mnt/c/Users/sos/medihunter/medicover_session.py", line 280, in check_response_correctness
    result.raise_for_status()
  File "/usr/lib/python3/dist-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: https://mol.medicover.pl/api/MyVisits/SearchFreeSlotsToBook?language=pl-PL
```
This terminate script and I need to rerun them after that

**Comment by JustAPhrog** [comment]
It looks like some medicover issue - not related to medihunter.

**Comment by apqlzm** [comment]
Is it the newest version of medihunter script? It looks like it's been customized :smile: 
Judging from HTTP code it looks like medicover server problem.
