### ISSUE TITLE
ModuleNotFoundError: No module named 'notifiers'

### ISSUE THREAD

**Issue by kalinowski5** [apqlzm/medihunter#4]
Po odpaleniu komendy `medihunter` dostaję taki błąd:

> Traceback (most recent call last):
  File "/usr/local/bin/medihunter", line 11, in <module>
    load_entry_point('medihunter', 'console_scripts', 'medihunter')()
  File "/usr/local/lib/python3.7/site-packages/pkg_resources/__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/local/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2793, in load_entry_point
    return ep.load()
  File "/usr/local/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2411, in load
    return self.resolve()
  File "/usr/local/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2417, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/Users/michal/Projekty/medihunter/medihunter.py", line 14, in <module>
    from medihunter_notifiers import pushover_notify
  File "/Users/michal/Projekty/medihunter/medihunter_notifiers.py", line 1, in <module>
    from notifiers import get_notifier
ModuleNotFoundError: No module named 'notifiers'

**Comment by apqlzm** [comment]
trzeba zainstalować notifiers
`pip install notifiers==1.0.3`
dodałem brakujący wpis do requirements.txt
